config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  authenticate :admin do
    resources :projects, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :projects, only: [:index, :show]

  root						   'static_pages#index'
  get 'projects' 			=> 'projects#index'
  get 'belief'              => 'static_pages#belief'
  get 'admin'               => 'admin#dashboard'
  get 'signin'				=> 'admins#sign_in'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
	  mount_uploader :image, ImageUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!

	def dashboard
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @latest = Project.last
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :subtitle, :description, :category, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		@hide_footer = true
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/dashboard.html.erb
This is the admin panel

<%= link_to 'log out', destroy_admin_session_path, :method => :delete, class: "button" %>

app/views/layouts/_footer.html.erb
<div class="row full small-collapse large-collapse" id="footer">

  <div class="small-12 columns img">
    <%= image_tag('footer/sunrise.jpg') %>
  </div>

  <div class= "row">
  	<div class="bottomlinks">
    <div class="small-12 medium-6 large-4 columns">
	  <small> © 2015 Shaun Yap  </small>
	</div>
	<div class="small-12 medium-6 large-4 columns">
	  <small> ABOUT </small>
	  <p> Asymmetric is Shaun Yap, a Singaporean Web Developer and Content Strategist based in Dubai. He lives on the internet.</p>
	</div>

	<div class="small-12 medium-6 large-4 columns">
	  <small> SITE MAP </small>
	  <dl>
	  	<dt><%= link_to 'Our belief', belief_path %></dt>
	  	<dt><%= link_to 'Work', projects_path %></dt>
	    <dt><a href='#'>Blog</a></dt>
	</dl>
    </div>
	</div>
  </div>
</div>

app/views/layouts/_sidenav.html.erb
<div id="small-sidebar" class="medium-12 columns">
        <div class="middle-header"> 
          <h2><%= link_to 'ASYMMETRIC', root_path %></h2>
          <%= link_to 'Our belief', belief_path, class:"button ghost" %> /
          <%= link_to 'Work', projects_path, class:"button ghost" %>/
          <a href="#" class="button ghost">Blog</a>
        </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Asymmetric returns for content" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row full">
      <%= render 'layouts/sidenav' %>
    </div>
          <%= yield %>
    

  <% if @hide_footer %>
  <% else %>    
      <%= render 'layouts/footer' %>
  <% end %>

  </body>
</html>

app/views/layouts/svg/_downarrow.html.erb
<svg class="arrows">
  <path class="a1" d="M0 0 L30 32 L60 0"></path>
  <path class="a2" d="M0 20 L30 52 L60 20"></path>
  <path class="a3" d="M0 40 L30 72 L60 40"></path>
</svg>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

   <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
<div class="small-1 medium-2 columns">&nbsp</div>
<div class="small-10 medium-8 columns">
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
<br /><br />

</div>
<div class="small-1 medium-2 columns">&nbsp</div>
</div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div id="offset-30">
<div class="row">
    <div class="small-12 medium-6 columns">
        <%= link_to image_tag(@latest.image_url), @latest %>
    </div>
    <div class="small-12 medium-6 columns">
        <h1><%= link_to @latest.name, @latest %></h1>
        <h4><%= @latest.subtitle %></h4>
    </div>
</div>
<br />

<div class="row">
  <% @projects.each do |project| %>
    <div class="large-3 medium-4 small-6 columns">
        <%= link_to image_tag(project.image_url), project %>
        <center>
        <h3><%= link_to project.name, project %></h3>
        <p><%= project.subtitle %></p></center>
    </div>
  <% end %>
</div>
<br />
<% if admin_signed_in? %>
<div class="row">
<%= link_to 'New Project', new_project_path, class:"button ghost small-4 medium-3 large-2" %>
</div>
<% end %>
<br />

</div>

app/views/projects/new.html.erb
<div class="row">
<div class="small-1 medium-2 columns">&nbsp</div>
<div class="small-10 medium-8 columns">
    <h1>New Project</h1>

      <%= render 'form' %>

      <%= link_to 'Back', projects_path %>
</div>
<div class="small-1 medium-2 columns">&nbsp</div>
</div>
</div>

app/views/projects/show.html.erb
<div class="row full" id="blackout">
  <center><div id="leadimage"><%= image_tag(@project.image_url) %></div></center>

  <div class="row">
    <div class="small-12 medium-8 large-4 large-centered medium-centered small-centered columns" id="coverpage">
      <h1><%= @project.name %></h1>
      <h4><%= @project.subtitle %></h4>
      <br /><br /><br /><br /><br />
      <%= render 'layouts/svg/downarrow' %>
    </div>
  </div>
</div>

<div class="writeup">
  <div class="row">
    <div class="small-12 large-10 large-centered columns">
      <h1>Challenge</h1>
      <p><%= @project.description %></p>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-10 large-centered columns">
      <h1>Strategy</h1>
      <p><%= @project.description %></p>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-10 large-centered columns">
      <h1>Execution</h1>
      <p><%= @project.description %></p>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-10 large-centered columns">
      <h1>Results</h1>
      <p><%= @project.description %></p>
    </div>
    <div class="small-12 columns">
      <%= link_to 'Edit', edit_project_path(@project) %> |
      <%= link_to 'Back', projects_path %> | 
      <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </div>  
  </div>
  <br />
</div>

app/views/static_pages/belief.html.erb
<div class="row">
    <br />
    <br />

  
  <div class="small-12 medium-6 large-4 columns">
    <center><%= image_tag("icons/insight.svg", width:256, height:256) %>
    <br />
    <h4>10x or go home</h4>
    <p>Working towards incremental improvements puts us in the rat race with everyone else. To set ourselves apart, we ask what would it look if it is an order of magnitude better?</p>
    </center>
  </div>

  <div class="small-12 medium-6 large-4 columns">
    <center><%= image_tag("icons/strategy.svg", width:256, height:256) %>
    <br />
    <h4>Force Multipliers</h4>
    <p>Not all factors are created equal. By identifying and then prioritizing the crucial few over the trivial many, we create an unfaiar advantage for ourselves.</p>
    </center>
  </div>

  <div class="small-12 medium-6 large-4  columns">
    <center><%= image_tag("icons/iterate.svg", width:256, height:256) %>
    <br />
    <h4>Abstract & Iterate</h4>
    <p>Content isn't building a bridge or launching a spaceship - we don't need all lights to be green before going ahead. Launch, abstract what works best, and iterate for continual improvement.</p>
    </center>
  </div>
  

</div>

app/views/static_pages/index.html.erb
<div class="row">
	<div class="small-12 columns" id="startpage">
	  <div class="headline">
        <p>The victorious strategist only seeks battle after the victory has been won - <i>Sun Tzu</i></p>
        <div class="small-12 columns">
          <h1>More content. Less marketing.</h1>
        </div>
        <div class="large-1 show-for-large-up columns">&nbsp</div>
        <div class="large-10 medium-12 columns">
          <p>Cut through the the sea of brands screaming for attention. Stack the odds in your favor - reach your audience with the right content in the right context. All it takes is a bit of Asymmetric Strategy.</p>
          <center><%= link_to 'Learn more', belief_path, class:"button ghost small-4" %></center>
        </div>
        <div class="large-1 show-for-large-up columns">&nbsp</div>
    </div>
  </div>
</div>